apiVersion: apps/v1
kind: Deployment
metadata: { name: taskflow-blue }
spec:
  replicas: 1
  selector: { matchLabels: { app: taskflow, color: blue } }
  template:
    metadata: { labels: { app: taskflow, color: blue } }
    spec:
      containers:
      - name: app
        image: localhost:5001/taskflow-api:init
        ports: [{ containerPort: 3000 }]
        envFrom: [{ secretRef: { name: taskflow-env } }]
        readinessProbe: { httpGet: { path: /health/live, port: 3000 } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: taskflow-green }
spec:
  replicas: 1
  selector: { matchLabels: { app: taskflow, color: green } }
  template:
    metadata: { labels: { app: taskflow, color: green } }
    spec:
      containers:
      - name: app
        image: localhost:5001/taskflow-api:init
        ports: [{ containerPort: 3000 }]
        envFrom: [{ secretRef: { name: taskflow-env } }]
        readinessProbe: { httpGet: { path: /health/live, port: 3000 } }
---
apiVersion: v1
kind: Service
metadata: { name: taskflow }
spec:
  selector: { app: taskflow, color: blue }
  ports: [{ port: 8080, targetPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: taskflow-blue }
spec:
  selector: { app: taskflow, color: blue }
  ports: [{ port: 8080, targetPort: 3000 }]
---
apiVersion: v1
kind: Service
metadata: { name: taskflow-green }
spec:
  selector: { app: taskflow, color: green }
  ports: [{ port: 8080, targetPort: 3000 }]